site_name: Self-Service
repo_url: https://github.com/systopia/de.systopia.selfservice
site_description: 'A guide for the Self-Service extension'
site_author: 'systopia'
theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Configuration': configuration.md
  - 'Use case': use-case.md
  - 'Security considerations': security-considerations.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
